openapi: 3.0.0
info:
  title: API First TypeScript demo
  version: "0.1"
  description: API First TypeScript demo
  contact:
    email: joachim.schirrmacher@deutschebahn.com
  license:
    name: Apache 2.0
servers:
  - url: "/"
    description: local

components:
  schemas:
    greeting:
      description: The data structure used by the hello world route
      type: object
      properties:
        greeting:
          type: string
          nullable: false
          pattern: 'Hello [A-Z]\w*!'
    answer:
      description: the answer
      type: object
      properties:
        answer:
          type: string
          nullable: false

  parameters:
    username:
      name: username
      in: query
      description: The user's name
      required: false
      schema:
        type: string
    question:
      name: question
      in: query
      description: question
      required: true
      schema:
        type: string

paths:
  /:
    get:
      description: Hello world route
      operationId: helloWorld
      parameters:
        - $ref: "#/components/parameters/username"
      responses:
        "200":
          description: Get data structure containing a greeting text
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/greeting"
    post:
      description: Send question
      operationId: getAnswer
      parameters:
        - $ref: "#/components/parameters/question"
      responses:
        "200":
          description: ask a question
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/answer"
                